### ISSUE TITLE
[Bug]: pip install minference error

### ISSUE THREAD

**Issue by junior-zsy** [microsoft/MInference#12]
### Describe the bug

pip install minference
Looking in indexes: https://mirrors.cloud.tencent.com/pypi/simple
Collecting minference
  Using cached https://mirrors.cloud.tencent.com/pypi/packages/26/0a/d4e339371c8b3673bd353ba51fdb55f381905f31daf2fb715d030d1d0c18/minference-0.1.3.tar.gz (57 kB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error
  
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [8 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/xxx/cache/tmp_dir/pip-install-6fkcqpqc/minference_6a95e304095b41bca85993d66c42b88e/setup.py", line 13, in <module>
          from torch.utils.cpp_extension import CUDA_HOME, BuildExtension, CUDAExtension
        File "/xxx/miniconda3/envs/minference/lib/python3.10/site-packages/torch/utils/cpp_extension.py", line 28, in <module>
          from pkg_resources import packaging  # type: ignore[attr-defined]
      ImportError: cannot import name 'packaging' from 'pkg_resources' (/xxx/miniconda3/envs/minference/lib/python3.10/site-packages/pkg_resources/__init__.py)
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.

**Comment by junior-zsy** [comment]
pip install setuptools==69.5.1  Solved my problem

**Comment by junior-zsy** [comment]
pip install setuptools==69.5.1  Solved my problem
