### ISSUE TITLE
[Question]: Run Local Qwen2-7B-Instruct Model Failed, show not supported。

### ISSUE THREAD

**Issue by wgimperial** [microsoft/MInference#34]
### Describe the issue

[rank0]: Traceback (most recent call last):
[rank0]:   File "/disk1/work/run_vllm.py", line 29, in <module>
[rank0]:     minference_patch = MInference("vllm", model_name)
[rank0]:   File "/root/miniconda3/envs/minference/lib/python3.10/site-packages/minference/models_patch.py", line 26, in __init__
[rank0]:     self.config = MInferenceConfig(
[rank0]:   File "/root/miniconda3/envs/minference/lib/python3.10/site-packages/minference/minference_configuration.py", line 42, in __init__
[rank0]:     self.config_path = self.update_config_path(config_path, model_name)
[rank0]:   File "/root/miniconda3/envs/minference/lib/python3.10/site-packages/minference/minference_configuration.py", line 57, in update_config_path
[rank0]:     model_name in MODEL2PATH
[rank0]: AssertionError: The model /data/huggingFace/Models/Qwen2-7B-Instruct/ you specified is not supported. You are welcome to add it and open a PR :)

**Comment by wgimperial** [comment]
vllm version 0.4.3  minference 0.1.4.post2
run_vllm.py  from https://github.com/microsoft/MInference/blob/main/examples/run_vllm.py

**Comment by iofu728** [comment]
Hi @wgimperial, thanks for your feedback.

You can try to set the `model_name=Qwen/Qwen2-7B-Instruct`.

**Comment by qingyuanxingsi** [comment]
+1 Please support local path!

**Comment by iofu728** [comment]
Since MInference does not manage model loading and cannot easily retrieve the actual model name from a local path, we are keeping this design as is. Please use the actual model name when calling MInference.
