### ISSUE TITLE
[Bug]: Can't install with pip install (Python 3.12, CUDA 12.6 Update 1, PyTorch 2.4.1)

### ISSUE THREAD

**Issue by atemerev** [microsoft/MInference#77]
### Describe the bug

Installed torch with `pip install torch`. Everything went fine. Then, while attempting to install minference with `pip install minference`, got the following error:
```
     Traceback (most recent call last):
        File "/usr/lib/python3.12/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
          main()
        File "/usr/lib/python3.12/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/usr/lib/python3.12/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 118, in get_requires_for_build_wheel
          return hook(config_settings)
                 ^^^^^^^^^^^^^^^^^^^^^
        File "/tmp/pip-build-env-dultiu8y/overlay/lib/python3.12/site-packages/setuptools/build_meta.py", line 332, in get_requires_for_build_wheel
          return self._get_build_requires(config_settings, requirements=[])
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/tmp/pip-build-env-dultiu8y/overlay/lib/python3.12/site-packages/setuptools/build_meta.py", line 302, in _get_build_requires
          self.run_setup()
        File "/tmp/pip-build-env-dultiu8y/overlay/lib/python3.12/site-packages/setuptools/build_meta.py", line 503, in run_setup
          super().run_setup(setup_script=setup_script)
        File "/tmp/pip-build-env-dultiu8y/overlay/lib/python3.12/site-packages/setuptools/build_meta.py", line 318, in run_setup
          exec(code, locals())
        File "<string>", line 11, in <module>
      ModuleNotFoundError: No module named 'torch'
      [end of output]
```

### Steps to reproduce

Fresh Fedora 40, fresh CUDA 12.6 Update 1 with cuda-gcc, fresh PyTorch 2.4.1.

### Expected Behavior

Pip install should work.

**Comment by iofu728** [comment]
Hi @atemerev, thanks for your feedback.

Could you try to install from source, as follow,

```bash
git clone https://github.com/microsoft/MInference
cd MInference
pip install -e .
```

**Comment by jacobgorm** [comment]
I am having the same problem with a different repo, I think the issue may be with pip or python, not the package. Were you able to make any progress?

**Comment by tanov25** [comment]
installing from source with --no-build-isolation flag helped
