### ISSUE TITLE
[Question]: What are the definitions of the different stages?

### ISSUE THREAD

**Issue by crazyofapple** [microsoft/MInference#98]
### Describe the issue

I would like to ask politely, what are the definitions of the different stages here? How to distinguish them? I am a novice in this field

ATTN_KV_TYPES=(
    "vllm;dense" # FullAttention
    "vllm_minference;dense" "vllm_a_shape;dense" "vllm_tri_shape;dense" # 1) KV Cache Generation Stage
    "dense;streamingllm" "dense;snapkv" "dense;pyramidkv" "dense;kivi" # 2) KV Cache Compression Stage
    "vllm_blend;dense" # 3) KV Cache Retrieval Stage
    "dense;quest" "dense;retr_attn" # 4) KV Cache Loading Stage
)

**Comment by iofu728** [comment]
Hi @crazyofapple, thanks for your interest in our work.  

These **four stages** are part of the **KV cache lifecycle** that we recently introduced in [**SCBench**](https://arxiv.org/abs/2412.10319). You can find the details in **Section 2** and **Figure 1**.  

![Onepage of SCBench](https://raw.githubusercontent.com/microsoft/MInference/main/images/SCBench_onepage.png)

**Comment by crazyofapple** [comment]
Thank you. I read the iclr submission before. Thank you for your excellent code base and timely response.

**Comment by iofu728** [comment]
Hi @crazyofapple, thanks for your question, and apologies for any confusion caused by unclear code.  

1. **`vllm_minference` vs. `minference`**: These are essentially the same. However, we recommend using **`vllm_minference`**, which integrates seamlessly with many optimization features in vLLM, such as TP and prefix caching. **`minference`** refers to the HF implementation.  

2. **`flash_attn` and `dense`**: These two are identical, both referring to the Flash Attention-2 kernel.  

3. **`retrieval_attn` in kv_type and attn_type**: Apologies for the oversight here. The option for `attn_type` should have been removed, as **RetrievalAttention** currently only supports **`kv_type="retr_attn"`**.  

Let me know if you have further questions!

**Comment by crazyofapple** [comment]
Thank you very much for your answer, which solved my question. BTW, I would like to ask about your VLLM version (mine is vllm==0.6.5, torch==2.5.1, python 3.12.4), because my current vllm_minference will report some errors.

**Comment by crazyofapple** [comment]
Also, I can't find a python package for `papyfaiss`. I understand your efforts to open source.

**Comment by iofu728** [comment]
Hi @crazyofapple,

I’ve been testing locally with vllm==0.6.0. I’ll check the higher versions soon. Could you share your error log? I’ll double-check if the specific error matches when I look into it later.

As for `papyfaiss`, it will be open-sourced at https://github.com/microsoft/RetrievalAttention. It’s currently undergoing internal code review.

**Comment by crazyofapple** [comment]
Many thanks for the reply. I changed to your version and it worked. The following is the error message for the higher version.


`[rank0]: Traceback (most recent call last):
[rank0]:   File "miniconda3/lib/python3.12/site-packages/vllm/worker/model_runner_base.py", line 116, in _wrapper
[rank0]:     return func(*args, **kwargs)
[rank0]:            ^^^^^^^^^^^^^^^^^^^^^
[rank0]:   File "miniconda3/lib/python3.12/site-packages/vllm/worker/model_runner.py", line 1683, in execute_model
[rank0]:     hidden_or_intermediate_states = model_executable(
[rank0]:                                     ^^^^^^^^^^^^^^^^^
[rank0]:   File "miniconda3/lib/python3.12/site-packages/torch/nn/modules/module.py", line 1736, in _wrapped_call_impl
[rank0]:     return self._call_impl(*args, **kwargs)
[rank0]:            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[rank0]:   File "miniconda3/lib/python3.12/site-packages/torch/nn/modules/module.py", line 1747, in _call_impl
[rank0]:     return forward_call(*args, **kwargs)
[rank0]:            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[rank0]:   File "miniconda3/lib/python3.12/site-packages/vllm/model_executor/models/llama.py", line 568, in forward
[rank0]:     model_output = self.model(input_ids, positions, kv_caches,
[rank0]:                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[rank0]:   File "miniconda3/lib/python3.12/site-packages/vllm/compilation/decorators.py", line 168, in __call__
[rank0]:     return self.forward(*args, **kwargs)
[rank0]:            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[rank0]: TypeError: minference_patch_vllm_executor.<locals>.llama_model_forward_vllm() takes from 5 to 6 positional arguments but 7 were given

[rank0]: The above exception was the direct cause of the following exception:

[rank0]: Traceback (most recent call last):
[rank0]:   File "ldf/MInference/scbench/run_scbench.py", line 392, in <module>
[rank0]:     pred = get_pred(
[rank0]:            ^^^^^^^^^
[rank0]:   File "ldf/MInference/scbench/run_scbench.py", line 125, in get_pred
[rank0]:     outputs = model.test(
[rank0]:               ^^^^^^^^^^^
[rank0]:   File "ldf/MInference/scbench/eval_utils.py", line 1148, in test
[rank0]:     result = self.llm.generate(
[rank0]:              ^^^^^^^^^^^^^^^^^^
[rank0]:   File "miniconda3/lib/python3.12/site-packages/vllm/utils.py", line 1025, in inner
[rank0]:     return fn(*args, **kwargs)
[rank0]:            ^^^^^^^^^^^^^^^^^^^
[rank0]:   File "miniconda3/lib/python3.12/site-packages/vllm/entrypoints/llm.py", line 454, in generate
[rank0]:     outputs = self._run_engine(use_tqdm=use_tqdm)
[rank0]:               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[rank0]:   File "miniconda3/lib/python3.12/site-packages/vllm/entrypoints/llm.py", line 1234, in _run_engine
[rank0]:     step_outputs = self.llm_engine.step()
[rank0]:                    ^^^^^^^^^^^^^^^^^^^^^^
[rank0]:   File "miniconda3/lib/python3.12/site-packages/vllm/engine/llm_engine.py", line 1405, in step
[rank0]:     outputs = self.model_executor.execute_model(
[rank0]:               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[rank0]:   File "miniconda3/lib/python3.12/site-packages/vllm/executor/gpu_executor.py", line 88, in execute_model
[rank0]:     output = self.driver_worker.execute_model(execute_model_req)
[rank0]:              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[rank0]:   File "miniconda3/lib/python3.12/site-packages/vllm/worker/worker_base.py", line 343, in execute_model
[rank0]:     output = self.model_runner.execute_model(
[rank0]:              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[rank0]:   File "miniconda3/lib/python3.12/site-packages/torch/utils/_contextlib.py", line 116, in decorate_context
[rank0]:     return func(*args, **kwargs)
[rank0]:            ^^^^^^^^^^^^^^^^^^^^^
[rank0]:   File "miniconda3/lib/python3.12/site-packages/vllm/worker/model_runner_base.py", line 152, in _wrapper
[rank0]:     raise type(err)(
[rank0]: TypeError: Error in model execution (input dumped to /tmp/err_execute_model_input_20241220-085214.pkl): minference_patch_vllm_executor.<locals>.llama_model_forward_vllm() takes from 5 to 6 positional arguments but 7 were given`

**Comment by crazyofapple** [comment]
@iofu728 BTW, I see that the results in your paper are all from a single method. Have you tried to combine different types of methods? If so, what did you find? If not, do you think this combination will have a future? I saw the improvement of snap+minference in the original minference paper, but it seems that there is no large-scale empirical result of the combination.

**Comment by iofu728** [comment]
Hi @crazyofapple,

That’s a great question! We haven’t conducted detailed research in this area, but I personally believe there’s potential for exploration and some interesting insights might be uncovered.

Currently, aside from the MInference w/ SnapKV results in MInference, there’s also MInference w/ ShadowKV provided by ShadowKV for reference.

**Comment by chaseblock** [comment]
> As for `papyfaiss`, it will be open-sourced at https://github.com/microsoft/RetrievalAttention. It’s currently undergoing internal code review.

@iofu728: Any idea what the timeline looks like for opening the RetrievalAttention repo?

Thanks for the effort in open sourcing this.

**Comment by iofu728** [comment]
Hi @chaseblock, Thanks for your support. 

We have completed the follow up work of RetrievalAttention and expect to release a new paper along with the corresponding code within the next one to two weeks.

**Comment by jagmarques** [comment]
To add to the combination discussion above: the four-stage taxonomy in SCBench maps to a useful mental model for thinking about stacking these methods. Stages 1 (generation-time sparse computation) and 2 (compression/eviction) are complementary by construction — MInference reduces FLOPs during prefill by computing sparse attention, while SnapKV/KIVI/PyramidKV reduce the KV footprint that gets written to cache. You can apply both: sparse prefill attention to reduce compute, then compress the resulting KV before writing it to the persistent cache.

The harder interaction is between Stage 2 (compression) and Stage 3/4 (retrieval). If you compress the KV cache with something like KIVI (per-channel 2-bit), then do retrieval-based attention (QUEST, RetrievalAttention), the retrieval index is built on compressed vectors, so retrieval quality degrades slightly. The question is whether the index precision loss exceeds the benefit from having 4–5x more tokens in cache.

One dimension missing from the current taxonomy: **vector quantization** as a Stage 2 method. The existing Stage 2 methods (SnapKV, KIVI, PyramidKV) all use scalar or channel-wise quantization. VQ-based methods like E8 lattice quantization achieve better rate-distortion at the same bit-width due to sphere packing, which means better retrieval quality at higher compression ratios. This might be worth adding to the SCBench evaluation grid if you're planning a follow-up — it would fill in the upper-right of the compression-quality Pareto frontier.
